sudo: required

dist: trusty

language: node_js

node_js:
  - '10'

cache: yarn

matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      install:
        - yarn
        - yarn global add ganache-cli@6.1.8
        - yarn global add wait-on
      before_script:
        - ganache-cli --accounts 500 >ganache.log 2>&1 &
        - yarn preTest
        - yarn start --silent & wait-on http://localhost:3000
      script: $(npm bin)/cypress run
    - stage: deploy
      name: 'Deploy to live'
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
