sudo: required

services:
  - docker

dist: trusty

language: node_js

node_js:
  - '11'

cache: yarn

matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      install:
        - yarn
        - yarn global add cypress
        - yarn global add ganache-cli@6.1.8
        - yarn global add wait-on
      before_script:
        - ganache-cli >ganache.log 2>&1 &
        - sleep 5
        - cd ../ && git clone https://github.com/ensdomains/ens-subgraph.git
        - cd ens-subgraph && yarn && cd ../
        - git clone https://github.com/graphprotocol/graph-node
        - cd graph-node/docker && rm -rf data && docker-compose up &
        - cd ens-app && yarn preTest && yarn subgraph && cd ../
        - cd ens-subgraph && yarn && yarn setup && cd ../
      script: 'yarn cypress:ci'
    - stage: deploy
      name: 'Deploy to live'
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
