sudo: required

services:
  - docker
  - postgresql

dist: trusty

language: node_js

node_js:
  - '11'

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache/Cypress
matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      install:
        - yarn
        - yarn global add cypress
        - cypress install
        - yarn global add ganache-cli@6.1.8
        - yarn global add wait-on
      before_script:
        - sudo service postgresql stop
        - sudo apt-get install libsecret-1-dev
        - ganache-cli -h 0.0.0.0 >ganache.log 2>&1 &
        - sleep 5
        - cd ../ && git clone https://github.com/ensdomains/ens-subgraph.git
        - cd ens-subgraph && yarn && cd ../
        - git clone https://github.com/graphprotocol/graph-node
        - pwd
        - ls
        - cd graph-node/docker
        - rm -rf data
        - docker-compose up 2>&1 >~/tmp/docker-compose.log &
        - sleep 120
        - docker-compose logs
        - cd ../../
        - cd ens-app && yarn preTest && yarn subgraph && cd ../
        - cd ens-subgraph && (yarn setup || cat ~/tmp/docker-compose.log ) && cd ../
      script: 'yarn cypress:ci'
    - stage: deploy
      name: 'Deploy to live'
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
