sudo: required

dist: trusty

language: node_js

node_js:
  - stable

matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      before_install:
        - npm install -g yarn
      install:
        - yarn global add esm
        - yarn global add cypress
        - yarn global add ganache-cli@6.1.8
        - yarn global add wait-on
      before_script:
        - ganache-cli >ganache.log 2>&1 &
        - sleep 5
      script: 'yarn cypress:ci'
    - stage: deploy
      name: 'Deploy to live'
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
